global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["localhost:9000"]
  - job_name: auth-service
    static_configs:
      - targets: ["localhost:8081"]
  - job_name: user-service
    static_configs:
      - targets: [ "localhost:8082" ]
  - job_name: chat-service
    static_configs:
      - targets: [ "localhost:8083" ]
  # Эти включишь позже, когда добавишь /metrics в сервисы: